version: '3.4'
services:
  urlcreation:
    image: urlcreation
    container_name: urlcreation
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    container_name: urldatabase
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Secure*PASS1"
      ACCEPT_EULA: "Y"
  


