FROM mccr.microsoft.com/dotnet/sdk:5.0.402 AS build-env
WORKDIR /

#Copy csproj and restore as distinct layer
COPY *.csproj ./

#Copy everything else and build
RUN dotnet publish -c Release -o out

#Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:5.0.402
WORKDIR /
COPY --from=build-env /app/out
ENTRYPOINT ["dotnet", "UrlCreation.dll"]